### ISSUE TITLE
Additional stuff

### ISSUE THREAD

**Issue by gedankenstuecke** [openSNP/opensnp_misc#1]
Shall we add posters/presentations here too, or shall I do another repo for that? :smiley:

**Comment by philippbayer** [comment]
Hmmm hard to say :) I still have the PLOS ONE paper repo too, i guess if it's already in a repo it can be moved?

**Comment by gedankenstuecke** [comment]
Yes, feel free to move the paper, your repository is origin right?

**Comment by philippbayer** [comment]
Looks like gedankenstuecke/opensnp_paper has newer commits than mine

**Comment by gedankenstuecke** [comment]
ah, it was fabians originally, so i just transferred mine :smiley:

**Comment by gedankenstuecke** [comment]
And I think I will just do two repos: One for talks, one for posters. Then we can share those as well. :)
