### ISSUE TITLE
What is plotted

### ISSUE THREAD

**Issue by gedankenstuecke** [openSNP/opensnp_misc#2]
I'm sightly confused, if you use the input as given in the README, won't it just plot the user-ID instead of the number of users (e.g. for users.R)?

**Comment by philippbayer** [comment]
Hmm yes that's possible - haven't looked at it in a while, did we even use these scripts? There's an XKCD script there :P

**Comment by gedankenstuecke** [comment]
Yeah, I think we never really used those scripts. :joy: Let me write another one later on.

**Comment by gedankenstuecke** [comment]
Ok, see #4
